### ISSUE TITLE
Is it possible to make multiple players without VPN? windows 2019 server

### ISSUE THREAD

**Issue by ExplosionMagicMegumin** [L-Leite/cso2-master-server#102]
Is it possible to make multiple players without VPN? windows 2019 server
What Is Necessary To Play Without VPN?

Windows Server 2019
![Ekran Alıntısı](https://user-images.githubusercontent.com/36341134/77828622-a1308500-712d-11ea-90b3-937f4ad06ec1.PNG)

**Comment by L-Leite** [comment]
Not at the time, I don't know what is needed to do this.
I'm closing this in favor of #47
