### ISSUE TITLE
I'm seriously impatient still no new build files *-*

### ISSUE THREAD

**Issue by ExplosionMagicMegumin** [L-Leite/cso2-master-server#110]
I'm seriously impatient still no new build files *-*

**Comment by dounai2333** [comment]
https://github.com/L-Leite/cso2-master-services/issues/39#issuecomment-634398751
do it before you ask, google is your friend.
**release version will only be released when project is in a stable status**. stable means this project can be running without common bugs or compatibility issues

**Comment by ExplosionMagicMegumin** [comment]
thanks
