### ISSUE TITLE
"Game server connection failed"

### ISSUE THREAD

**Issue by DarkConqueror2002** [L-Leite/cso2-master-server#112]
Hi, i have tried countless times trying to startup and play Counter Strike Online 2 and to no prevail. I keep getting "Game server connection failed" over and over and over idk if it's my internet or something else. I followed "CSOmanias" guide on youtube on installing CSO and he seems to not reply to most of his comments. If someone has a solution please help me and others too!
![server connection failed](https://user-images.githubusercontent.com/67183056/85195618-167da300-b2a2-11ea-9482-214722323780.png)

**Comment by dounai2333** [comment]
you forget to setup the server or missing [-masterip](https://github.com/L-Leite/cso2-launcher#available-command-line-arguments) in the launcher, example in cmd: start X:\cso2\Bin\launcher.exe -masterip 127.0.0.1

**Comment by DarkConqueror2002** [comment]
> you forget to setup the server or missing [-masterip](https://github.com/L-Leite/cso2-launcher#available-command-line-arguments) in the launcher, example in cmd: start X:\cso2\Bin\launcher.exe -masterip 127.0.0.1

How do i do what you said?

**Comment by DarkConqueror2002** [comment]
Still doesn't work

**Comment by DarkConqueror2002** [comment]
Do you have a discord? i think i need help with this. I think when i setup my server i do it automatically with the custom launcher in CSOmania cso update video and for the Masterip do i use my ip address?

**Comment by DarkConqueror2002** [comment]
I found the problem basically you launch the game through this launcher and you type in your ip address through "start-cso2.bat" it didn't work for me b4 bc i was using the wrong launcher.
