### ISSUE TITLE
You can't use the Human Strengthening Laboratory.

### ISSUE THREAD

**Issue by cso2** [L-Leite/cso2-master-server#16]
![cso2_0004](https://user-images.githubusercontent.com/44349391/50544519-82e28d80-0c3b-11e9-9b92-9affd3c96edc.jpg)
The score does not rise and it is impossible to save.

**Comment by DebugBios** [comment]
Is this a feature that requires a database?

**Comment by Ochii** [comment]
> 
> 
> Is this a feature that requires a database?

Probably, I haven't looked into it
