### ISSUE TITLE
Chat not available.

### ISSUE THREAD

**Issue by DebugBios** [L-Leite/cso2-master-server#23]
Chatting is not currently available.

**Comment by DebugBios** [comment]
If you can chat, can you add a command to send a server message?

**Comment by Ochii** [comment]
The client seems to send the chat message to the master server.

The master server must send the message back to the host in order to fix this

**Comment by DebugBios** [comment]
I think I asked the wrong question.

Can you use commands such as sm_say?

There was a function of posting in the chat window and at the top of the screen.

**Comment by Ochii** [comment]
No, because I don't load any sourcemod modules

**Comment by DebugBios** [comment]
![ba f2 bd c3 bc ad b9 f6 c1 be b7 e1](https://user-images.githubusercontent.com/44349391/52167730-01fb4200-2763-11e9-9f50-9315c0461a43.jpg)

Like the image, does this mean that the notice function is unavailable?

**Comment by DebugBios** [comment]
unknown packet id 67 from ed70cdfc-fccf-4d12-820e-ce97522e5f2c

**Comment by awsl1** [comment]
@Ochii 
Chatting system doesn't work.
I typed something in the chat dialog,but nothing happened.

**Comment by JusicP** [comment]
Packet 67 its Packet_UMsg

**Comment by L-Leite** [comment]
Fixed in #107, special messages are not available though
