### ISSUE TITLE
Can't use instant respawns or health kits in Zombie Crush

### ISSUE THREAD

**Issue by DebugBios** [L-Leite/cso2-master-server#39]
#38 
![cso2_0000](https://user-images.githubusercontent.com/44349391/52523332-8f92e080-2cd3-11e9-9c51-3ef7b865e80e.jpg)

You can write only one item.

We will need to add more items. 

Also, the skill items are no longer used.

**Comment by Ochii** [comment]
Which items do you recommend I should use? (At least until the database is implemented)

**Comment by DebugBios** [comment]
[선택형] This is no longer used.



With one play, you can use 50 회복 캡슐
Once played, you can use three 즉시부활권

**Comment by DebugBios** [comment]
회복캡슐 It is not available.

UserManager::onHostPacket: unknown host packet type 105

**Comment by DebugBios** [comment]
By any chance, can you increase the number of items to 400?

If the mode is to be played several times, more numbers are required.

**Comment by kr1staa** [comment]
![MJJW_)LG0J6B%N$GC%7HGC5](https://user-images.githubusercontent.com/47288667/55678207-35577a00-5928-11e9-9a53-ce194db43f45.png)
Only four roles can use health packs,but it can consume up to two.
