### ISSUE TITLE
Dedicated server support

### ISSUE THREAD

**Issue by organnerx** [L-Leite/cso2-master-server#47]
How this master server works - it responsible for games list, inventories, rooms list and games' starting. But it is not responsible for games' hosting! Games' hosting should be the main priority of master server. There is more detailed explanation:
You host master server on dedicated server with an external IP. Then, when player without external IP creates a room on that master server, other players can enter his lobby successfully because this is what master server do. But when the game is started, it is being hosted on this host-player 192.168.0.1 / 127.0.0.1 / localhost IP. So all players who were waited for game start are kicked with connection error (error 2004).
All games on master server should be hosted with the same IP as master server. It should just increment a port number for each room and not use players' IP's for hosting. So room's IP's will look like xxxxx:30001, xxxxx:30002, xxxxx:30003, etc. This is how it is done in CSO1 and maybe was done in CSO2. This will give an ability to play online while having only the master server IP.

**Comment by Riseless** [comment]
+1

**Comment by gnexia2013** [comment]
+1

**Comment by gnexia2013** [comment]
I have external IP ，But so do others.2004，2001，7004

**Comment by gnexia2013** [comment]
Stuck in% 15 or 10%

**Comment by ChenyuHou** [comment]
You can use OpenVPN 
create a server 
all players connect it
DCHP server must open

**Comment by Kawaii-Maou-Sama** [comment]
still no improvement?

**Comment by L-Leite** [comment]
> still no improvement?

i haven't looked into this yet
