### ISSUE TITLE
Update channels room lists

### ISSUE THREAD

**Issue by organnerx** [L-Leite/cso2-master-server#52]
Possible enhancement:
Currently, master server is sending room list only if you join a channel, but if you are just hanging in channel and waiting for the games you won't see that new rooms being created. You will need to leave channel and enter it again.
Maybe need to implement some time interval - send every 10 seconds new room list to everyone who is hanging on channel.

**Comment by Ochii** [comment]
The event of a new room could trigger a room list update to everyone in the room's channel

**Comment by leang97** [comment]
Please check out https://github.com/leang97/cso2-master-server/blob/master/src/channel/channelmanager.ts

I created a users list which will push update to the waiting users in room list every time someone makes changes to the room settings, it is not the best but it would work right now. You can port the functions to Ochii's original repo.
