### ISSUE TITLE
Cannot play missing game modes

### ISSUE THREAD

**Issue by cso2** [L-Leite/cso2-master-server#62]
https://youtu.be/r4O1fbSyDCc

Also, copying of players can happen.

**Comment by Ochii** [comment]
The game fails to start the match and sends a CSO2_ModFileDoesnotExist message to the user

The master server isn't checking if the game mode is missing

**Comment by Ochii** [comment]
The game does this in order to check that the game mode exists:

```c++
bool DoesGamemodeExist( int16_t iModType, const char* szModName,
                        const char* szMapName, int8_t iLevel = 0 )
{
    if ( !g_pFilesystem )
    {
        return false;
    }

    if ( !szModName || szModName[0] == 0 )
    {
        return false;
    }

    if ( !szMapName || szMapName[0] == 0 )
    {
        return false;
    }

    char szPathBuffer[260];
    szPathBuffer[0] = 0;

    if ( iModType == 1 )
    {
        V_snprintf( szPathBuffer, sizeof( szPathBuffer ),
                    "scripts/mod/%s/%s/%s.elo", szModName, szMapName,
                    szMapName );
    }
    else if ( iModType == 2 )
    {
        V_snprintf( szPathBuffer, sizeof( szPathBuffer ),
                    "scripts/mod/%s/%s_lvl%d/%s_lvl%d.elo", szModName,
                    szMapName, iLevel, szMapName, iLevel );
    }
    else
    {
        V_snprintf( szPathBuffer, sizeof( szPathBuffer ),
                    "scripts/mod/%s/mod_%s.elo", szModName, szModName );
    }

    return g_pFilesystem->FileExists( szPathBuffer, "MOD" );
}
```

```c++
  // somewhere in the game's ui code
  /* ... */
  bool bGamemodeExists = DoesGamemodeExist(modType, modName, mapName, level);
  if ( bGamemodeExists )
    /* start the match */
  else
    showUiWarning(74, "#CSO2_ModFileDoesnotExist", 1);
  /* ... */
```

**Comment by Ochii** [comment]
Can you test [0.8.14](https://github.com/Ochii/cso2-master-server/releases/tag/0.8.14)? @dounai2333's PR should fix this

**Comment by DebugBios** [comment]
The error has not been corrected.

**Comment by DebugBios** [comment]
The host's privileges are retained when it enters the ghost room again. But when I leave the room, it won't shut down.

**Comment by Ochii** [comment]
Do you have the game mode(s) elo files installed?

**Comment by DebugBios** [comment]
I didn't put the lo file in the custom file.

**Comment by DebugBios** [comment]
https://youtu.be/N_LjOiXbPwI

**Comment by DebugBios** [comment]
https://youtu.be/s2K78iBhMYM.

If you put a custom file in, it's still the same.

**Comment by Ochii** [comment]
Seems to be an issue with the launcher. Can you send me the custom files you're using?

**Comment by DebugBios** [comment]
[scripts.zip](https://github.com/Ochii/cso2-master-server/files/3051126/scripts.zip)

**Comment by dounai2333** [comment]
in fact, I didn't add modes that are not currently playable (https://github.com/Ochii/cso2-master-server/issues/45), I didn't stop any players trying to start the can not be played modes request
currently, Heroes can be fixed by porting the Japanese version of the client, so it should not be disable, however, since the current Korean version of the client does not have a Heroes mode file, it will prompt "the game can not be start, because the current mode is not available" when countdown over, that is why we had this BUG
