### ISSUE TITLE
Missing user's information

### ISSUE THREAD

**Issue by cso2** [L-Leite/cso2-master-server#72]
Profile icon and name number cannot be worn. 
It is also impossible to set up a change in the lobby.

Also, removing "Enter one word of the day" and inserting other characters will not save.

![cso2_0001](https://user-images.githubusercontent.com/44349391/54101861-2ce35080-4409-11e9-8c84-98c98e12d594.jpg)
![cso2_0000](https://user-images.githubusercontent.com/44349391/54101862-2ce35080-4409-11e9-91a6-37f7251b91b0.jpg)

**Comment by CCasusensa** [comment]
you mean this? @DebugBios 

 ![](http://i.imgur.com/ZMj1VLw.jpg)
 ![](http://i.imgur.com/XyoCRur.jpg)
 ![](http://i.imgur.com/xbrFLNe.jpg)
 ![](http://i.imgur.com/eXt7Crv.jpg)

**Comment by DebugBios** [comment]
@CCasusensa 
How can the function be used?

I have a server version of 0.8.11

**Comment by CCasusensa** [comment]
@DebugBios

you just understand the packet then code

**Comment by ChenyuHou** [comment]
@CCasusensa 
Can you share your master-server film

**Comment by organnerx** [comment]
@CCasusensa Hello. Can you please share your user info packet reversing work for me? I will credit you properly on my website. Thanks

**Comment by felixabi** [comment]
+1 user info packet reversing
