### ISSUE TITLE
Cannot join server when kicked through the console

### ISSUE THREAD

**Issue by cso2** [L-Leite/cso2-master-server#77]
When deported to the console, it returns to the first screen and when you click on a server, infinite loading occurs.

**Comment by Ochii** [comment]
Are you talking about the 'kick' command in the console?

**Comment by DebugBios** [comment]
Yes

**Comment by DebugBios** [comment]
https://youtu.be/Ve9p1tW264M

**Comment by DebugBios** [comment]
cso2_test_kickvote "(name)"

You can use the to cause that error right away.

**Comment by DebugBios** [comment]
https://youtu.be/fo-FU3KWRQA

**Comment by cso2** [comment]
21475 CN Client 0.5.2 Launcher

The same bug occurs when using cso2mon_kill after sv_cheats 1
