### ISSUE TITLE
Suggestions And Requests

### ISSUE THREAD

**Issue by felixabi** [L-Leite/cso2-master-server#98]
Suggestions And Requests

1=User Account Password Change.
2=.php support for web app | example: home.php playerinfo.php passwordchange.php resetpassword.php
3=V.S V.S Announcement = https://i.hizliresim.com/odl47b.png
4=Executive GM Account
5=Room Kick Or Similar Function
6=Chat and Voice Chat
7=Opening more than 1 channel, for example: 
-------------------------
1-Rookie Server 
2-Master Server
-------------------------
8=Live Broadcast Department Work: https://i.hizliresim.com/p5VJXr.png
9=Quick Start Quick start Function Does Not Show or Find Rooms. : https://i.hizliresim.com/7BZ3qN.png
10=Adding weapons to the store
11=Combination  :https://i.hizliresim.com/kMRdbq.png
12=Server Name > Room Number 01 https://i.hizliresim.com/odl4kX.png
13=Create Clan Clan Search Clan Icons
14=Coupon Code - Point Milage And Cash : https://i.hizliresim.com/XbpRE5.png

**Comment by DebugBios** [comment]
Although chatting is not available, I know that voice chatting is possible.

**Comment by L-Leite** [comment]
Thanks for the write up, I have added these points as notes in [this project](https://github.com/L-Leite/cso2-master-services/projects/1)

Number 12 is being tracked in issue L-Leite/cso2-master-services#17
